### ISSUE TITLE
MySQL connection

### ISSUE THREAD

**Issue by Dmitry-Kucher** [janKir/bgio-postgres#9]
First of all - Thank you for your connector to the Postgres Database.

It's not documented, but there is an option to connect to MySQL database using `bgio-postgres`

The following example is showing how to use MySQL (tested on 5.7 version):

```
import { Server } from "boardgame.io/server";
import TicTacToe from "./game";
import { PostgresStore } from "bgio-postgres";

const db = new PostgresStore({
    database: "bgio-test",
    username: "bgio",
    password: "superstrongpassword",
    host: "localhost",
    dialect: "mysql",
});

const server = Server({
    games: [TicTacToe],
    db,
});

server.run(8000);
```

Also you need to manually install mysql2 package. i.e. execute: `npm install --save mysql2`

The only difference from the standard example is to pass `dialect` options.

So, the question is: maybe it would be better to rename PostgresStore to something more general SequelizeStore/SQLStore or something else to show that it is not only for the Postgres (but not sure what to do with the package name)
As well, [here](https://github.com/janKir/bgio-postgres/blob/master/src/postgres.ts#L16) let to pass dialect options with the URI to the database.

All of this also applicable for MSSQL, SQLite, MariaDB with appropriate package of connector [see more](https://sequelize.org/master/manual/getting-started.html#installing)

Hope it would be helpful for someone

**Comment by janKir** [comment]
Thanks for your input! You address an interesting point here and I am sure this might help others as well!

I think your suggestions can be divided into 2 parts:

*1. the compatibility for other dialects should be "officially" supported and maybe even be reflected in a more general library name*

I am hesistant in doing so because I think this will probably increase the maintenance effort and complexity. Some things like the connector packages and column data types differ for each dialect. Also, we currently use the [`JSON` data type](https://sequelize.org/master/manual/other-data-types.html) which is not supported by all available engines.

*2. it should be documented that this library can also be tweeked for use with other db engines*

I am happy to add a short section to the README describing your approach for the use of MySQL (and other dialects). We should make it clear there, that this is not officially supported (and can't be guaranteed to work like this in the future - although I wouldn't know why). And also that this doesn't work for all dialects (due to the JSON field).

Are you willing to create a PR for that?

**Comment by Alex23rodriguez** [comment]
I noticed this same thing and found this issue. I've gone ahead and created the PR because i'd have liked to see it on the Readme. It's worth noting that i've tested this successfully on [a project](https://github.com/Alex23rodriguez/liamazons-server/blob/main/src/server.ts) and haven't run into any issues.
